
-- Drop existing tables, types, and functions to start fresh
-- The CASCADE option will remove any dependent objects as well.
DROP FUNCTION IF EXISTS "public"."get_total_billed"(p_user_id uuid);
DROP FUNCTION IF EXISTS "public"."get_monthly_income"(p_user_id uuid);
DROP FUNCTION IF EXISTS "public"."get_workload_by_category"(p_user_id uuid);
DROP FUNCTION IF EXISTS "public"."get_client_leaderboard"(p_user_id uuid);

DROP TABLE IF EXISTS "public"."page_content" CASCADE;
DROP TABLE IF EXISTS "public"."portfolio_items" CASCADE;
DROP TABLE IF EXISTS "public"."portfolio_categories" CASCADE;
DROP TABLE IF EXISTS "public"."tasks" CASCADE;
DROP TABLE IF EXISTS "public"."projects" CASCADE;
DROP TABLE IF EXISTS "public"."clients" CASCADE;
DROP TABLE IF EXISTS "public"."testimonials" CASCADE;
DROP TABLE IF EXISTS "public"."notifications" CASCADE;

DROP TYPE IF EXISTS "public"."project_status";
DROP TYPE IF EXISTS "public"."task_status";
DROP TYPE IF EXISTS "public"."task_priority";
DROP TYPE IF EXISTS "public"."notification_type";

-- Recreate Types
CREATE TYPE "public"."project_status" AS ENUM ('planning', 'in-progress', 'completed');
CREATE TYPE "public"."task_status" AS ENUM ('todo', 'in-progress', 'done');
CREATE TYPE "public"."task_priority" AS ENUM ('low', 'medium', 'high');
CREATE TYPE "public"."notification_type" AS ENUM ('new_client', 'new_project', 'task_due', 'project_completed');

-- Recreate Tables
CREATE TABLE "public"."clients" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL,
    "name" text NOT NULL,
    "email" text NOT NULL,
    "avatar" text,
    "status" text DEFAULT 'new'::text,
    "company" text,
    "phone" text,
    "address" text,
    "notes" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."clients" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX clients_pkey ON public.clients USING btree (id);
ALTER TABLE "public"."clients" ADD CONSTRAINT "clients_pkey" PRIMARY KEY USING INDEX "clients_pkey";
ALTER TABLE "public"."clients" ADD CONSTRAINT "clients_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE TABLE "public"."projects" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "title" text NOT NULL,
    "description" text,
    "status" public.project_status DEFAULT 'planning'::public.project_status,
    "client_id" uuid,
    "budget" numeric,
    "start_date" date,
    "end_date" date,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_pkey" PRIMARY KEY USING INDEX "projects_pkey";
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;


CREATE TABLE "public"."tasks" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "title" text NOT NULL,
    "description" text,
    "status" public.task_status DEFAULT 'todo'::public.task_status,
    "priority" public.task_priority DEFAULT 'medium'::public.task_priority,
    "due_date" date,
    "project_id" bigint,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_pkey" PRIMARY KEY USING INDEX "tasks_pkey";
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;


CREATE TABLE "public"."portfolio_categories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "user_id" uuid NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."portfolio_categories" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX portfolio_categories_pkey ON public.portfolio_categories USING btree (id);
ALTER TABLE "public"."portfolio_categories" ADD CONSTRAINT "portfolio_categories_pkey" PRIMARY KEY USING INDEX "portfolio_categories_pkey";
ALTER TABLE "public"."portfolio_categories" ADD CONSTRAINT "portfolio_categories_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


CREATE TABLE "public"."portfolio_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "title" text NOT NULL,
    "slug" text NOT NULL,
    "description" text,
    "fullDescription" text,
    "image" text,
    "hint" text,
    "tags" text[],
    "category" text,
    "link" text,
    "screenshots" text[],
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."portfolio_items" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX portfolio_items_pkey ON public.portfolio_items USING btree (id);
CREATE UNIQUE INDEX portfolio_items_slug_key ON public.portfolio_items USING btree (slug);
ALTER TABLE "public"."portfolio_items" ADD CONSTRAINT "portfolio_items_pkey" PRIMARY KEY USING INDEX "portfolio_items_pkey";
ALTER TABLE "public"."portfolio_items" ADD CONSTRAINT "portfolio_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE TABLE "public"."notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "type" public.notification_type NOT NULL,
    "title" text NOT NULL,
    "description" text,
    "link" text,
    "is_read" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);
ALTER TABLE "public"."notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY USING INDEX "notifications_pkey";
ALTER TABLE "public"."notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE TABLE "public"."page_content" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "section" text NOT NULL,
    "content" jsonb,
    "user_id" uuid NOT NULL
);
ALTER TABLE "public"."page_content" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX page_content_pkey ON public.page_content USING btree (id);
CREATE UNIQUE INDEX page_content_section_user_id_key ON public.page_content USING btree (section, user_id);
ALTER TABLE "public"."page_content" ADD CONSTRAINT "page_content_pkey" PRIMARY KEY USING INDEX "page_content_pkey";
ALTER TABLE "public"."page_content" ADD CONSTRAINT "page_content_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


CREATE TABLE "public"."testimonials" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "name" text NOT NULL,
    "company" text,
    "feedback" text NOT NULL,
    "avatar" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."testimonials" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX testimonials_pkey ON public.testimonials USING btree (id);
ALTER TABLE "public"."testimonials" ADD CONSTRAINT "testimonials_pkey" PRIMARY KEY USING INDEX "testimonials_pkey";
ALTER TABLE "public"."testimonials" ADD CONSTRAINT "testimonials_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


-- Set up Row Level Security (RLS)
-- Clients
CREATE POLICY "Enable read access for authenticated users" ON "public"."clients" FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users" ON "public"."clients" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."clients" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."clients" FOR DELETE USING (auth.uid() = user_id);

-- Projects
CREATE POLICY "Enable read access for authenticated users" ON "public"."projects" FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users" ON "public"."projects" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."projects" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."projects" FOR DELETE USING (auth.uid() = user_id);

-- Tasks
CREATE POLICY "Enable read access for authenticated users" ON "public"."tasks" FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users" ON "public"."tasks" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."tasks" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."tasks" FOR DELETE USING (auth.uid() = user_id);

-- Portfolio Items (Publicly readable, but only editable by the owner)
CREATE POLICY "Enable read access for all users" ON "public"."portfolio_items" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."portfolio_items" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."portfolio_items" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."portfolio_items" FOR DELETE USING (auth.uid() = user_id);

-- Portfolio Categories (Publicly readable)
CREATE POLICY "Enable read access for all users" ON "public"."portfolio_categories" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."portfolio_categories" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."portfolio_categories" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."portfolio_categories" FOR DELETE USING (auth.uid() = user_id);

-- Page Content (Publicly readable)
CREATE POLICY "Enable read access for all users" ON "public"."page_content" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."page_content" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."page_content" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."page_content" FOR DELETE USING (auth.uid() = user_id);

-- Testimonials (Publicly readable)
CREATE POLICY "Enable read access for all users" ON "public"."testimonials" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."testimonials" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."testimonials" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."testimonials" FOR DELETE USING (auth.uid() = user_id);

-- Notifications (Private)
CREATE POLICY "Enable access for authenticated users" ON "public"."notifications" FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- Seed Data
-- This script will seed the database with initial data for a single user.
-- Replace 'YOUR_USER_ID' with the actual user ID from the auth.users table.
-- You can get your user ID by running `select id from auth.users limit 1;` in the Supabase SQL editor after you've signed up.
-- If the table is empty, sign up in your app first.
DO $$
DECLARE
    user_id_to_seed uuid;
    client_1_id uuid;
    client_2_id uuid;
    client_3_id uuid;
    project_1_id bigint;
    project_2_id bigint;
    project_3_id bigint;
    web_cat_id bigint;
    mobile_cat_id bigint;
    design_cat_id bigint;
BEGIN
    -- This will seed data for the first user found in the auth.users table.
    -- Ensure you have at least one user signed up before running this.
    SELECT id INTO user_id_to_seed FROM auth.users LIMIT 1;

    IF user_id_to_seed IS NULL THEN
        RAISE EXCEPTION 'No users found in auth.users. Please sign up a user in your application first.';
    END IF;

    -- Seed Clients
    INSERT INTO public.clients(user_id, name, email, avatar, status, company, phone, address, notes) VALUES
    (user_id_to_seed, 'Innovate Inc.', 'contact@innovate.com', 'https://i.pravatar.cc/100?u=innovate', 'active', 'Innovate Inc.', '555-0101', '123 Tech Avenue, Silicon Valley', 'Leading tech startup working on next-gen AI platforms. Key contact is Jane Doe.')
    RETURNING id INTO client_1_id;
    
    INSERT INTO public.clients(user_id, name, email, avatar, status, company, phone, address, notes) VALUES
    (user_id_to_seed, 'Creative Solutions', 'hello@creative.co', 'https://i.pravatar.cc/100?u=creative', 'active', 'Creative Solutions LLC', '555-0102', '456 Design Drive, Arts District', 'Award-winning design agency specializing in branding and UX. They appreciate bold designs.')
    RETURNING id INTO client_2_id;

    INSERT INTO public.clients(user_id, name, email, avatar, status, company, phone, address, notes) VALUES
    (user_id_to_seed, 'Global Goods', 'support@globalgoods.com', 'https://i.pravatar.cc/100?u=global', 'new', 'Global Goods', '555-0103', '789 Market Street, Commerce City', 'New client in the e-commerce space. Looking for a full website overhaul and mobile app.')
    RETURNING id INTO client_3_id;

    -- Seed Projects
    INSERT INTO public.projects(user_id, title, description, status, client_id, budget, start_date, end_date) VALUES
    (user_id_to_seed, 'Website Redesign', 'Complete overhaul of the corporate website for Innovate Inc.', 'in-progress', client_1_id, 25000, '2023-08-01', '2023-12-15')
    RETURNING id INTO project_1_id;

    INSERT INTO public.projects(user_id, title, description, status, client_id, budget, start_date, end_date) VALUES
    (user_id_to_seed, 'Mobile App Launch', 'Launch campaign and app development for the new mobile application for Creative Solutions.', 'planning', client_2_id, 40000, '2023-09-15', '2024-01-30')
    RETURNING id INTO project_2_id;

    INSERT INTO public.projects(user_id, title, description, status, client_id, budget, start_date, end_date) VALUES
    (user_id_to_seed, 'E-commerce Integration', 'Integrating a new payment gateway and inventory system for Innovate Inc.', 'completed', client_1_id, 15000, '2023-06-01', '2023-07-30')
    RETURNING id INTO project_3_id;
    
    -- Seed Tasks
    INSERT INTO public.tasks(user_id, project_id, title, status, priority, due_date) VALUES
    (user_id_to_seed, project_1_id, 'Finalize homepage UX/UI', 'in-progress', 'high', (now() + interval '7 day')),
    (user_id_to_seed, project_1_id, 'Develop about us page', 'todo', 'medium', (now() + interval '14 day')),
    (user_id_to_seed, project_2_id, 'Create app store screenshots', 'todo', 'high', (now() + interval '10 day')),
    (user_id_to_seed, project_2_id, 'Plan marketing campaign', 'in-progress', 'high', (now() + interval '5 day')),
    (user_id_to_seed, project_2_id, 'User testing & feedback session', 'todo', 'medium', (now() + interval '30 day')),
    (user_id_to_seed, project_3_id, 'Payment gateway sandbox testing', 'done', 'high', (now() - interval '20 day'));

    -- Seed Portfolio Categories
    INSERT INTO public.portfolio_categories (user_id, name) VALUES
    (user_id_to_seed, 'Web'),
    (user_id_to_seed, 'Mobile'),
    (user_id_to_seed, 'Design')
    RETURNING id, id, id INTO web_cat_id, mobile_cat_id, design_cat_id;

    -- Seed Portfolio Items
    INSERT INTO public.portfolio_items (user_id, title, slug, description, "fullDescription", image, hint, tags, category, link, screenshots) VALUES
    (user_id_to_seed, 'E-commerce Platform', 'e-commerce-platform', 'A robust and scalable e-commerce solution with a focus on user experience.', 'This project involved building a full-featured e-commerce platform from the ground up. Key features include a product catalog, shopping cart, secure checkout process, and an admin dashboard for managing products and orders. The frontend was built with Next.js and Tailwind CSS for a fast, responsive experience, while the backend relies on Supabase for data and authentication.', 'https://picsum.photos/seed/project1/800/600', 'online store', '{"Next.js", "React", "Supabase", "Stripe", "Tailwind CSS"}', 'Web', '#', '{"https://picsum.photos/seed/s1a/800/600", "https://picsum.photos/seed/s1b/800/600", "https://picsum.photos/seed/s1c/800/600"}'),
    (user_id_to_seed, 'Travel Companion App', 'travel-companion-app', 'A mobile app to help users plan trips and discover new places.', 'The Travel Companion App is a native mobile application for iOS and Android. It allows users to create itineraries, book flights and hotels, and discover local attractions with user reviews and ratings. I was responsible for the full UI/UX design process in Figma and the frontend development in React Native.', 'https://picsum.photos/seed/project2/800/600', 'travel map', '{"React Native", "Figma", "UI/UX", "Mobile"}', 'Mobile', '#', '{"https://picsum.photos/seed/s2a/800/600", "https://picsum.photos/seed/s2b/800/600"}'),
    (user_id_to_seed, 'Branding for a Startup', 'branding-for-startup', 'A complete brand identity design for a new tech startup.', 'This project was a deep dive into brand strategy and visual identity. I worked closely with the startup''s founders to develop their mission, vision, and values, which then informed the logo design, color palette, typography, and marketing materials. The result is a cohesive and memorable brand that stands out in a competitive market.', 'https://picsum.photos/seed/project3/800/600', 'logo design', '{"Branding", "Logo Design", "Figma", "Illustration"}', 'Design', '#', '{"https://picsum.photos/seed/s3a/800/600"}');

    -- Seed Page Content
    INSERT INTO public.page_content (user_id, section, content) VALUES
    (user_id_to_seed, 'hero', '{"title": "Creative Developer & Designer", "subtitle": "MOHAMED AREF", "description": "I build beautiful, functional, and accessible digital experiences.", "background": "orb"}'),
    (user_id_to_seed, 'about', '{"title": "Mohamed Aref", "description": "I am a passionate developer and designer with a knack for creating things that are both beautiful and useful.", "skills": ["Next.js", "React", "TypeScript", "Node.js", "Supabase", "Tailwind CSS", "Figma", "UI/UX Design"], "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_n8R-S22Q-23v_h_2k2l_v0w_zX_zX_zX_zX=s176-c-k-c0x00ffffff-no-rj"}'),
    (user_id_to_seed, 'process', '[
        {"icon": "MessageCircle", "title": "Discovery & Strategy", "description": "We start by understanding your vision, goals, and audience to build a solid foundation.", "color": "text-blue-500"},
        {"icon": "Lightbulb", "title": "Ideation & Design", "description": "Creative solutions and user-centric designs are brought to life through wireframes and mockups.", "color": "text-yellow-500"},
        {"icon": "PencilRuler", "title": "Prototyping", "description": "Interactive prototypes are created to test and refine the user experience before development.", "color": "text-orange-500"},
        {"icon": "Code", "title": "Development", "description": "Clean, efficient code is written to build a fast, scalable, and reliable product.", "color": "text-green-500"},
        {"icon": "Combine", "title": "Testing & QA", "description": "Rigorous testing across devices ensures a bug-free and seamless user experience.", "color": "text-purple-500"},
        {"icon": "Rocket", "title": "Launch & Iterate", "description": "The product is deployed, and I monitor its performance, ready to iterate based on user feedback.", "color": "text-pink-500"}
    ]'),
    (user_id_to_seed, 'socials', '{"phone": "tel:+1234567890", "whatsapp": "https://wa.me/1234567890", "facebook": "https://facebook.com", "instagram": "https://instagram.com", "twitter": "https://twitter.com", "linkedin": "https://linkedin.com"}');

    -- Seed Testimonials
    INSERT INTO public.testimonials(user_id, name, company, feedback, avatar) VALUES
    (user_id_to_seed, 'Alice Johnson', 'TechCorp', 'Working with Mohamed was a fantastic experience. He delivered a high-quality product on time and was incredibly responsive to feedback.', 'https://i.pravatar.cc/100?u=alice'),
    (user_id_to_seed, 'Bob Williams', 'Innovate Inc.', 'The final result exceeded our expectations. The design is modern, and the application is incredibly fast and intuitive. Highly recommended!', 'https://i.pravatar.cc/100?u=bob');

    -- Seed Notifications
    INSERT INTO public.notifications (user_id, type, title, description, link) VALUES
    (user_id_to_seed, 'new_client', 'New Client Added', 'Global Goods has been added to your clients list.', '/admin/clients'),
    (user_id_to_seed, 'task_due', 'Task Overdue', 'Finalize homepage UX/UI is now overdue.', '/admin/tasks'),
    (user_id_to_seed, 'project_completed', 'Project Completed', 'E-commerce Integration has been marked as complete.', '/admin/projects');

END $$;


-- Define RPC functions for reports
CREATE OR REPLACE FUNCTION public.get_total_billed(p_user_id uuid)
RETURNS numeric
LANGUAGE sql
AS $$
    SELECT COALESCE(SUM(budget), 0)
    FROM public.projects
    WHERE user_id = p_user_id AND status = 'completed';
$$;

CREATE OR REPLACE FUNCTION public.get_monthly_income(p_user_id uuid)
RETURNS TABLE(name text, income numeric)
LANGUAGE sql
AS $$
    WITH months AS (
      SELECT generate_series(
        date_trunc('year', now()),
        date_trunc('year', now()) + '11 months'::interval,
        '1 month'::interval
      )::date AS month
    )
    SELECT
      to_char(m.month, 'Mon') as name,
      COALESCE(SUM(p.budget), 0) AS income
    FROM months m
    LEFT JOIN public.projects p ON date_trunc('month', p.end_date) = m.month AND p.user_id = p_user_id AND p.status = 'completed'
    GROUP BY m.month
    ORDER BY m.month;
$$;

CREATE OR REPLACE FUNCTION public.get_workload_by_category(p_user_id uuid)
RETURNS TABLE(name text, value integer)
LANGUAGE sql
AS $$
    SELECT 
        pc.name,
        count(pi.id)::integer as value
    FROM public.portfolio_categories pc
    LEFT JOIN public.portfolio_items pi ON pc.name = pi.category AND pi.user_id = p_user_id
    WHERE pc.user_id = p_user_id
    GROUP BY pc.name;
$$;

CREATE OR REPLACE FUNCTION public.get_client_leaderboard(p_user_id uuid)
RETURNS TABLE(client_id uuid, client_name text, client_company text, total_value numeric)
LANGUAGE sql
AS $$
    SELECT
        c.id as client_id,
        c.name as client_name,
        c.company as client_company,
        COALESCE(SUM(p.budget), 0) as total_value
    FROM public.clients c
    JOIN public.projects p ON c.id = p.client_id
    WHERE c.user_id = p_user_id AND p.status = 'completed'
    GROUP BY c.id, c.name, c.company
    ORDER BY total_value DESC
    LIMIT 5;
$$;

