
-- Drop tables in reverse order of creation to respect foreign key constraints.
DROP TABLE IF EXISTS "public"."notifications";
DROP TABLE IF EXISTS "public"."tasks";
DROP TABLE IF EXISTS "public"."projects";
DROP TABLE IF EXISTS "public"."clients";
DROP TABLE IF EXISTS "public"."testimonials";
DROP TABLE IF EXISTS "public"."page_content";
DROP TABLE IF EXISTS "public"."portfolio_categories";
DROP TABLE IF EXISTS "public"."portfolio_items";

-- Drop existing functions to ensure they are re-created correctly.
DROP FUNCTION IF EXISTS "public"."get_total_billed"(p_user_id uuid);
DROP FUNCTION IF EXISTS "public"."get_monthly_income"(p_user_id uuid);
DROP FUNCTION IF EXISTS "public"."get_workload_by_category"(p_user_id uuid);
DROP FUNCTION IF EXISTS "public"."get_client_leaderboard"(p_user_id uuid);


-- Create Clients Table
CREATE TABLE "public"."clients" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "name" character varying NOT NULL,
    "email" character varying NOT NULL,
    "avatar" text,
    "status" character varying DEFAULT 'new'::character varying,
    "company" character varying,
    "phone" character varying,
    "address" text,
    "notes" text,
    "user_id" uuid,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."clients" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for authenticated users" ON "public"."clients" FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users" ON "public"."clients" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."clients" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."clients" FOR DELETE USING (auth.uid() = user_id);

-- Create Projects Table
CREATE TABLE "public"."projects" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" character varying NOT NULL,
    "description" text,
    "status" character varying DEFAULT 'planning'::character varying,
    "client_id" uuid,
    "budget" real,
    "start_date" date,
    "end_date" date,
    "user_id" uuid,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE SET NULL
);
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for authenticated users" ON "public"."projects" FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users" ON "public"."projects" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."projects" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."projects" FOR DELETE USING (auth.uid() = user_id);

-- Create Tasks Table
CREATE TABLE "public"."tasks" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "description" text,
    "status" character varying DEFAULT 'todo'::character varying,
    "priority" character varying DEFAULT 'medium'::character varying,
    "due_date" date,
    "project_id" bigint,
    "user_id" uuid,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for authenticated users" ON "public"."tasks" FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users" ON "public"."tasks" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."tasks" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."tasks" FOR DELETE USING (auth.uid() = user_id);

-- Create Notifications Table
CREATE TABLE "public"."notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL,
    "type" character varying NOT NULL,
    "title" character varying NOT NULL,
    "description" text,
    "link" text,
    "is_read" boolean DEFAULT false,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for authenticated users" ON "public"."notifications" FOR ALL USING (auth.uid() = user_id);

-- Create Portfolio Categories Table
CREATE TABLE "public"."portfolio_categories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" character varying NOT NULL UNIQUE,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."portfolio_categories" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all users" ON "public"."portfolio_categories" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."portfolio_categories" FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users" ON "public"."portfolio_categories" FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users" ON "public"."portfolio_categories" FOR DELETE USING (auth.role() = 'authenticated');


-- Create Portfolio Items Table
CREATE TABLE "public"."portfolio_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" character varying NOT NULL,
    "slug" character varying NOT NULL UNIQUE,
    "description" text,
    "fullDescription" text,
    "image" text,
    "hint" text,
    "link" text,
    "tags" text[],
    "category" character varying,
    "screenshots" text[],
    "user_id" uuid,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."portfolio_items" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all users" ON "public"."portfolio_items" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."portfolio_items" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."portfolio_items" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."portfolio_items" FOR DELETE USING (auth.uid() = user_id);

-- Create Page Content Table
CREATE TABLE "public"."page_content" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "section" character varying NOT NULL UNIQUE,
    "content" jsonb,
    "user_id" uuid,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."page_content" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all users" ON "public"."page_content" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."page_content" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."page_content" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."page_content" FOR DELETE USING (auth.uid() = user_id);

-- Create Testimonials Table
CREATE TABLE "public"."testimonials" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" character varying NOT NULL,
    "company" character varying,
    "feedback" text NOT NULL,
    "avatar" text,
    "user_id" uuid,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."testimonials" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all users" ON "public"."testimonials" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."testimonials" FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for authenticated users" ON "public"."testimonials" FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for authenticated users" ON "public"."testimonials" FOR DELETE USING (auth.uid() = user_id);


-- Insert Demo Data
-- Note: You may need to update the user_id with your actual Supabase user's UID.
-- You can find this in the Supabase dashboard under Authentication -> Users.

-- Portfolio Categories
INSERT INTO "public"."portfolio_categories" (name) VALUES ('Web'), ('Mobile'), ('Design');

-- Page Content
INSERT INTO "public"."page_content" (section, content) VALUES
('hero', '{"title": "Creative Developer & Designer", "subtitle": "MOHAMED AREF", "description": "I build beautiful, functional, and accessible digital experiences.", "background": "orb"}'),
('about', '{"title": "Mohamed Aref", "description": "I am a passionate developer and designer with a knack for creating things that are both beautiful and useful.", "skills": ["Next.js", "React", "TypeScript", "Node.js", "Supabase", "Tailwind CSS", "Figma", "UI/UX Design"], "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_n8R-S22Q-23v_h_2k2l_v0w_zX_zX_zX_zX=s176-c-k-c0x00ffffff-no-rj"}'),
('process', '[{"icon":"MessageCircle","title":"Discovery & Strategy","description":"We start by understanding your goals, audience, and challenges.","color":"text-blue-500"},{"icon":"Lightbulb","title":"Ideation & Concepts","description":"Next, we brainstorm and explore creative directions for the project.","color":"text-orange-500"},{"icon":"PencilRuler","title":"Design & Prototyping","description":"I create wireframes, mockups, and interactive prototypes.","color":"text-pink-500"},{"icon":"Code","title":"Development & Code","description":"I bring the designs to life with clean, efficient code.","color":"text-green-500"},{"icon":"Combine","title":"Testing & Refinement","description":"Rigorous testing ensures a bug-free, polished experience.","color":"text-purple-500"},{"icon":"Rocket","title":"Launch & Optimization","description":"The project goes live! I monitor performance and optimize.","color":"text-yellow-500"}]');

-- Testimonials
INSERT INTO "public"."testimonials" (name, company, feedback, avatar) VALUES
('Alice Johnson', 'TechCorp', 'Working with Mohamed was a fantastic experience. He delivered a high-quality product on time and was incredibly responsive to feedback.', 'https://i.pravatar.cc/100?u=alice'),
('Bob Williams', 'Innovate Inc.', 'The final result exceeded our expectations. The design is modern, and the application is incredibly fast and intuitive. Highly recommended!', 'https://i.pravatar.cc/100?u=bob');

-- Insert demo clients, projects, etc. linked to a user.
-- This requires a valid user_id from your auth.users table.
-- Replace 'your-user-id-here' with an actual user ID after a user has signed up.
-- Example of how to add user-specific data:
/*
WITH user_info AS (
    SELECT id FROM auth.users LIMIT 1
),
inserted_client AS (
    INSERT INTO public.clients (name, email, avatar, status, company, phone, address, notes, user_id)
    SELECT 'Innovate Inc.', 'contact@innovate.com', 'https://i.pravatar.cc/100?u=innovate', 'active', 'Innovate Inc.', '555-0101', '123 Tech Avenue, Silicon Valley', 'Leading tech startup.', user_info.id
    FROM user_info
    RETURNING id, user_id
)
INSERT INTO public.projects (title, description, status, client_id, budget, start_date, end_date, user_id)
SELECT 'Website Redesign', 'Complete overhaul of the corporate website.', 'in-progress', inserted_client.id, 50000, '2024-05-01', '2024-08-31', inserted_client.user_id
FROM inserted_client;
*/


-- Database Functions for Reports

CREATE OR REPLACE FUNCTION get_total_billed(p_user_id uuid)
RETURNS real
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN (
    SELECT COALESCE(SUM(budget), 0)
    FROM projects
    WHERE user_id = p_user_id AND status = 'completed'
  );
END;
$$;


CREATE OR REPLACE FUNCTION get_monthly_income(p_user_id uuid)
RETURNS TABLE(name text, income real)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    to_char(months.month, 'Mon') as name,
    COALESCE(SUM(p.budget), 0)::real as income
  FROM 
    generate_series(
      date_trunc('year', now()), 
      date_trunc('year', now()) + interval '11 months', 
      interval '1 month'
    ) as months(month)
  LEFT JOIN 
    projects p ON date_trunc('month', p.end_date) = months.month
               AND p.user_id = p_user_id
               AND p.status = 'completed'
  GROUP BY 
    months.month
  ORDER BY 
    months.month;
END;
$$;


CREATE OR REPLACE FUNCTION get_workload_by_category(p_user_id uuid)
RETURNS TABLE(name character varying, value integer)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    pi.category AS name,
    COUNT(pi.id)::integer AS value
  FROM 
    portfolio_items pi
  WHERE 
    pi.user_id = p_user_id
  GROUP BY 
    pi.category;
END;
$$;

CREATE OR REPLACE FUNCTION get_client_leaderboard(p_user_id uuid)
RETURNS TABLE(id uuid, client_name character varying, client_company character varying, total_value real)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    c.id,
    c.name as client_name,
    c.company as client_company,
    COALESCE(SUM(p.budget), 0)::real as total_value
  FROM 
    clients c
  LEFT JOIN 
    projects p ON c.id = p.client_id AND p.status = 'completed'
  WHERE 
    c.user_id = p_user_id
  GROUP BY 
    c.id, c.name, c.company
  ORDER BY 
    total_value DESC
  LIMIT 5;
END;
$$;


    
